### ISSUE TITLE
Default repo field

### ISSUE THREAD

**Issue by benmccann** [svitejs/changesets-changelog-github-compact#45]
### Describe the problem

Currently you need to do `"changelog": ["@svitejs/changesets-changelog-github-compact", { "repo": "sveltejs/eslint-config" }],`. I realized though that the default changesets formatter doesn't require you to pass `repo`

### Describe the proposed solution

I wonder if we could make it simpler to setup by just automatically getting the repo the same way as the default formatter

### Alternatives considered

Status quo

### Importance

nice to have

**Comment by dominikg** [comment]
this is based on their `changelog-github` which also requires you to provide the repo 
https://github.com/changesets/changesets/blob/main/packages/changelog-github/src/index.ts#L14

we may be able to read it from root package.json instead but that could be brittle.

**Comment by benmccann** [comment]
Ah, I see. I didn't realize they have a separate `@changesets/changelog-git` and `@changesets/changelog-github`

Yeah, reading it from the `package.json` seems potentially tricky, so probably not worth trying that

Thanks!
