### ISSUE TITLE
Smaller commit hash like github?

### ISSUE THREAD

**Issue by nooblyf** [svitejs/changesets-changelog-github-compact#55]
### Describe the problem

Instead of using the full commit hash is there a setting to use just the first seven characters just for the text part? 🙂

![Screenshot 2024-07-26 at 17 27 40](https://github.com/user-attachments/assets/8c27ba09-1c16-4b08-8766-2aba4fff6c46)

### Describe the proposed solution

Like how GitHub does it, they are using the first 7 characters from commit hash

![Screenshot 2024-07-26 at 17 27 49](https://github.com/user-attachments/assets/d96ae774-5d42-4ee9-91e2-3d6553655c9f)

For example, here's how it looks after using first 7 characters only

![Screenshot 2024-07-26 at 17 34 42](https://github.com/user-attachments/assets/0e503e23-a2d5-4c0f-af19-1a4b4f1f8174)

### Alternatives considered

Manually updating it when PR is created

### Importance

nice to have

**Comment by Hdoc1509** [comment]
Hi, @nooblyf 

After a deep dive through this PR https://github.com/changesets/changesets/pull/1236, I found that this package just needs to:

- update `@changesets/get-github-info` to `0.6.0`
- apply `.slice(0,7)` to [first `commitFromSummary` in `getReleaseLine()`](https://github.com/vimcaw/changesets-changelog-github-compact-with-integration/blob/e509ceb4c75a8098db0c210b21f0986f26d9d7a2/packages/changesets-changelog-github-compact/src/index.ts#L80), like [this implementation of `@changesets/changelog-github`](https://github.com/changesets/changesets/blob/dfd4cca84118df913feedfeac37a4939566ae447/packages/changelog-github/src/index.ts#L81-L85)

### Additional note

I tested locally and it works as expected.

I will add it this changes to one of my projects and link it here in a few hours.

**Comment by nooblyf** [comment]
nvm, i was able to achieve it with a local script

**Comment by dominikg** [comment]
you should at least use a longer slice than 8, a collision can occur more likely with each char you cut

**Comment by Hdoc1509** [comment]
> you should at least use a longer slice than 8, a collision can occur more likely with each char you cut

Do you mean a collision in generated link?

**Comment by dominikg** [comment]
yes

**Comment by Hdoc1509** [comment]
Well, that case is covered by `@changesets/get-github-info@0.6.0`.

I [made this implementation](https://github.com/Hdoc1509/tree-sitter-hygen-template/blob/78ffa4ed5b0b9786f9bcd5a919b26d55771acb98/.changeset/with-updated-github-info.cjs) and used it for [this CHANGELOG.md at v0.2.3](https://github.com/Hdoc1509/tree-sitter-hygen-template/blob/v0.2.3/CHANGELOG.md).

Is this enough for publish a new version with these updates?

Thanks for reading  n_n7

**Comment by nooblyf** [comment]
collision probability is extremely low even with 7 chars isn't it?

there are 36 possible chars (0-9a-z) in commit hash so 36^7 = ~78.4 Billion combinations. it would take ~40K IDs, in order to have a 1% probability of at least one collision

or am i missing something?

**Comment by nooblyf** [comment]
collision probability is very low even with 7 chars isn't it?

there are 36 possible chars (0-9a-z) in commit hash so 36^7 = ~78.4 Billion combinations. it would take ~40K IDs, in order to have a 1% probability of at least one collision

or am i missing something?

**Comment by dominikg** [comment]
we had collisions with short hashes in vite-ecosystem-ci, better to use the short hash only in the label and full hash in the url. PR welcome. this repo is pretty low prio for me, ideally it's features found it's way back to changesets itself, feel free to raise your voice in their repo

**Comment by Hdoc1509** [comment]
Yes. The short hash will only be used for label. Generated URL will remain intact.

**Comment by dominikg** [comment]
released in 1.2.0, thanks!

**Comment by Hdoc1509** [comment]
You're welcome. n_n7
